export const ALL_COURSE_LIST = "ALL_COURSE_LIST";
export const CHAPTER_LIST = "CHAPTER_LIST";
export const LESSON_LIST = "LESSON_LIST";
export const BATCH_REMOVE_CHAPTER_LIST = "BATCH_REMOVE_CHAPTER_LIST";
export const BATCH_REMOVE_LESSON_LIST = "BATCH_REMOVE_LESSON_LIST";
